# Generated by Django 2.2.1 on 2019-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190629_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
